/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.asiakastilaus;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Denis Bogdanov
 */
public class Asiakastilaus extends javax.swing.JFrame {

    /**
     * Creates new form Asiakastilaus1
     */
    public Asiakastilaus() {
        initComponents();
    }
    public Connection luoYhteys()
    {
        Connection cn=null;
        
    try {
        cn = DriverManager.
                getConnection("jdbc:mariadb://" + "localhost" + ":3306/ASIAKASTILAUS", "kehittaja", "Koira123!");
        return cn;
    } catch (SQLException e){
        System.out.println("Yhteyden luominen epäonnistui!:\n" + e.getMessage());
        e.printStackTrace();
        return null;
    }
    }
    public void sulje(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chkSalasana = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtTunnus = new javax.swing.JTextField();
        jbtnKirjaudu = new javax.swing.JButton();
        jtxtSalana = new javax.swing.JPasswordField();
        jbtnTestaa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        chkSalasana.setText("Näytä salasana");
        chkSalasana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSalasanaActionPerformed(evt);
            }
        });

        jLabel1.setText("Tervetuloa Asiakas-tietojärjestelmään.");

        jLabel2.setText("Tunnus:");

        jLabel3.setText("Salasana");

        jtxtTunnus.setText("HeikkiHuoltohenkilO2");

        jbtnKirjaudu.setText("Kirjaudu");
        jbtnKirjaudu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKirjauduActionPerformed(evt);
            }
        });

        jtxtSalana.setText("KiSsa123#!");
        jtxtSalana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSalanaActionPerformed(evt);
            }
        });

        jbtnTestaa.setText("Testata");
        jbtnTestaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTestaaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxtTunnus, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                    .addComponent(jtxtSalana)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jbtnKirjaudu)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnTestaa)
                            .addComponent(chkSalasana, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtTunnus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(chkSalasana)
                    .addComponent(jtxtSalana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnKirjaudu)
                    .addComponent(jbtnTestaa))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnKirjauduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnKirjauduActionPerformed
        // TODO add your handling code here:
        String tunnus = jtxtTunnus.getText();
        String oikeasalasanatietokannassa = "";
        
        char annettusalasana[] = jtxtSalana.getPassword();
        char [] oikeasalasanataulukkona = null;
        
        Connection cn = luoYhteys();
        
        String sqlKysely = "SELECT TUNNUS, DES_DECRYPT(SALASANA, 'salainenavain') AS SALASANA FROM KAYTTAJA WHERE TUNNUS='"+tunnus+"'";
        //jtxtSQL.setText(sqlKysely);
        try {
            PreparedStatement stm = cn.prepareStatement(sqlKysely);
            ResultSet tulos = stm.executeQuery();
            
            if(tulos.next()) {
                oikeasalasanatietokannassa = tulos.getString("SALASANA").trim();  
                oikeasalasanataulukkona = oikeasalasanatietokannassa.toCharArray();
                
                if(Arrays.equals(annettusalasana, oikeasalasanataulukkona)){
                    GUI g = new GUI(tunnus);
                    g.setVisible(true);
                    sulje();
                } else {
                    JOptionPane.showMessageDialog(this,"Tunnus tai salasana on väärin. Yritä uudelleen.");
                    jtxtTunnus.requestFocus();
                    return;
                } 
            }
        } catch (SQLException ex) {
            Logger.getLogger(Asiakastilaus.class.getName()).log(Level.SEVERE, null, ex);
        }
        Arrays.fill(oikeasalasanataulukkona, '0');
        oikeasalasanatietokannassa="";
    }//GEN-LAST:event_jbtnKirjauduActionPerformed

    private void jtxtSalanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSalanaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSalanaActionPerformed

    private void chkSalasanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSalasanaActionPerformed
        // TODO add your handling code here:
        if(chkSalasana.isSelected()){
            jtxtSalana.setEchoChar((char)0);
            chkSalasana.setSelected(true);
        } else {
            jtxtSalana.setEchoChar('+');
            chkSalasana.setSelected(false);  
        }
    }//GEN-LAST:event_chkSalasanaActionPerformed

    private void jbtnTestaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTestaaActionPerformed
        // TODO add your handling code here:
        try { 
        Class.forName("org.mariadb.jdbc.Driver"); 
    } catch (ClassNotFoundException e) { 
      System.out.println("Missä on MariaDB JDBC ajuri? Oletko ladannut mariadb connectorin osoitteesta: https://mariadb.com/downloads/#connectors ja lisännyt sen Netbeansissä Asiakasrekisteri-Libraries-Add JAR/Folder kohdassa?"); 
      e.printStackTrace(); 
      return; 
    } 
     System.out.println("Mariadb JDBC Driver rekisteröity!"); 
     Connection connection = null; 
     
    try { 
     connection = DriverManager. 
       getConnection("jdbc:mariadb://" + "localhost:" + "3306/ASIAKASTILAUS", "kehittaja", "Koira123!"); 
    } catch (SQLException e) { 
    System.out.println("Yhteyden luominen epäonnistui!:\n" + e.getMessage()); 
    } 
    if (connection != null) { 
    System.out.println("Hienoa ja onnittelut! Sait luotua yhteyden tietokantaasi. Voit aloittaa käyttöliittymän koodaamisen!"); 
    } else { 
    System.out.println("Pahus, tarkista vielä, että kaikki tarvittava on tehty ja virheitä ei ole!"); 
    } 
    }//GEN-LAST:event_jbtnTestaaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asiakastilaus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asiakastilaus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asiakastilaus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asiakastilaus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Asiakastilaus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkSalasana;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbtnKirjaudu;
    private javax.swing.JButton jbtnTestaa;
    private javax.swing.JPasswordField jtxtSalana;
    private javax.swing.JTextField jtxtTunnus;
    // End of variables declaration//GEN-END:variables
}
